CTForces/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.views.generic import RedirectView

from website.admin import custom_admin_site

urlpatterns = [
    path('admin/', custom_admin_site.urls),

    re_path('^favicon\.ico$',
            RedirectView.as_view(url=settings.FAVICON_PATH, permanent=True)),

    re_path('^apple-touch-icon\.png$',
            RedirectView.as_view(url=settings.APPLE_TOUCH_ICON_PATH, permanent=True)),

    re_path('^apple-touch-icon-precomposed\.png$',
            RedirectView.as_view(url=settings.APPLE_TOUCH_ICON_PRECOMPOSED_PATH, permanent=True)),

    re_path('^', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns = [
                      re_path(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

urlpatterns += [re_path('^silk/', include('silk.urls', namespace='silk'))]

website/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.static import serve

from .views import *

urlpatterns = [
    re_path('^$', MainView.as_view(), name='main_view'),
    path('page/<int:page>/', MainView.as_view(), name='main_view_with_page'),

    re_path('^signup/$', UserRegistrationView.as_view(), name='signup'),
    re_path('^signin/$', UserLoginView.as_view(), name='signin'),
    re_path('^logout/$', logout_user, name='logout'),

    path('user/<str:username>/', UserInformationView.as_view(), name='user_info'),

    re_path('^settings/general/$', SettingsGeneralView.as_view(), name='settings_general_view'),
    re_path('^settings/social/$', SettingsSocialView.as_view(), name='settings_social_view'),

    re_path('^friends/$', FriendsView.as_view(), name='friends_view'),
    path('friends/page/<int:page>/', FriendsView.as_view(), name='friends_view_with_page'),

    re_path('^search_users/$', search_users, name='user_search'),

    path('user/<str:username>/blog/', UserBlogView.as_view(), name='user_blog_view'),
    path('user/<str:username>/blog/page/<int:page>/', UserBlogView.as_view(), name='user_blog_view_with_page'),
    path('user/<str:username>/tasks/', UserTasksView.as_view(), name='user_tasks_view'),
    path('user/<str:username>/tasks/page/<int:page>/', UserTasksView.as_view(), name='user_tasks_view_with_page'),
    path('user/<str:username>/contests/', UserContestListView.as_view(), name='user_contests_view'),
    path('user/<str:username>/contests/page/<int:page>/', UserContestListView.as_view(),
         name='user_contests_view_with_page'),

    path('user/<str:username>/solved_tasks/', UserSolvedTasksView.as_view(),
         name='user_solved_tasks_view'),
    path('user/<str:username>/solved_tasks/page/<int:page>/', UserSolvedTasksView.as_view(),
         name='user_solved_tasks_view_with_page'),

    path('top_users/', UserTopView.as_view(), name='users_top_view'),
    path('top_users/page/<int:page>/', UserTopView.as_view(), name='users_top_view_with_page'),

    path('top_rating_users/', UserRatingTopView.as_view(), name='users_rating_top_view'),
    path('top_rating_users/page/<int:page>/', UserRatingTopView.as_view(), name='users_rating_top_view_with_page'),

    path('top_rating_users_by_group/', UserByGroupRatingTopView.as_view(), name='users_by_group_rating_top_view'),
    path('top_rating_users_by_group/page/<int:page>/', UserByGroupRatingTopView.as_view(),
         name='users_by_group_rating_top_view_with_page'),

    re_path('^add_post/$', PostCreationView.as_view(), name='post_creation_view'),
    path('post/<int:post_id>/', PostView.as_view(), name='post_view'),

    re_path('^leave_comment/$', leave_comment, name='leave_comment'),

    re_path('^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),

    path('task/<int:task_id>/', TaskView.as_view(), name='task_view'),
    path('task/<int:task_id>/edit/', TaskEditView.as_view(), name='task_edit_view'),
    path('task/<int:task_id>/submit/', submit_task, name='task_submit'),
    path('task/<int:task_id>/solved/', TaskSolvedView.as_view(), name='task_solved_view'),
    path('task/<int:task_id>/solved/page/<int:page>/', TaskSolvedView.as_view(), name='task_solved_view_with_page'),

    re_path('^create_task/$', TaskCreationView.as_view(), name='task_creation_view'),

    re_path('^tasks/$', TasksArchiveView.as_view(), name='task_archive_view'),
    path('tasks/page/<int:page>/', TasksArchiveView.as_view(), name='task_archive_view_with_page'),

    re_path('^confirm_email/$', account_confirmation, name='confirm_account'),
    re_path('^resend_email/$', EmailResendView.as_view(), name='resend_email_view'),

    re_path('^password_reset_email/$', PasswordResetEmailView.as_view(), name='password_reset_email'),
    re_path('^reset_password/$', PasswordResetPasswordView.as_view(), name='password_reset_password'),

    re_path('^search_tags/$', search_tags, name='search_tags'),
    re_path('^get_task/$', get_task, name='get_task_by_id'),

    re_path('^create_contest/$', ContestCreationView.as_view(), name='create_contest'),

    path('contests/', ContestsMainListView.as_view(), name='contests_main_list_view'),
    path('contests/page/<int:page>/', ContestsMainListView.as_view(), name='contests_main_list_view_with_page'),

    path('contest/<int:contest_id>/', ContestMainView.as_view(), name='contest_view'),
    path('contest/<int:contest_id>/register/', register_for_contest, name='register_for_contest'),
    path('contest/<int:contest_id>/scoreboard/', ContestScoreboardView.as_view(), name='contest_scoreboard_view'),
    path('contest/<int:contest_id>/task/<int:task_id>/', ContestTaskView.as_view(), name='contest_task_view'),
    path('contest/<int:contest_id>/task/<int:task_id>/submit/', submit_contest_flag, name='contest_task_submit'),

    re_path('^test', test_view, name='test_view'),
    re_path('^debug', debug_view, name='debug_view'),
]

website/models.py
from celery import current_app
from django.contrib.auth.models import AbstractUser, Group
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models
from django.utils.datetime_safe import datetime
from django_countries.fields import CountryField
from guardian.shortcuts import assign_perm
from mptt.models import TreeForeignKey, MPTTModel
from stdimage.models import StdImageField
from stdimage.validators import MaxSizeValidator

from website.tasks import start_contest, end_contest
from .models_auxiliary import CustomUploadTo, CustomImageSizeValidator, CustomFileField, stdimage_processor


class User(AbstractUser):
    class Meta:
        permissions = (
            ('view_tasks_archive', 'Can view user\'s tasks archive'),
            ('view_contests_archive', 'Can view user\'s contests archive'),
        )

    username_validator = ASCIIUsernameValidator()

    organization = models.ForeignKey(
        'Organization',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='users'
    )

    rank = models.IntegerField(blank=False, default=0)
    rating = models.IntegerField(blank=False, default=2000)
    max_rating = models.IntegerField(blank=False, default=2000)

    country = CountryField(blank_label='(select country)', null=True, blank=True)
    city = models.CharField(max_length=256, blank=True)
    friends = models.ManyToManyField('User', related_name='befriended_by', blank=True, symmetrical=False)

    last_solve = models.DateTimeField(null=True)

    avatar = StdImageField(
        upload_to=CustomUploadTo(
            upload_type='avatars',
            path='',
            random_filename=True),
        variations={
            'main': (300, 300),
            'small': (100, 100)
        },
        validators=[
            CustomImageSizeValidator(
                min_limit=(150, 150),
                max_limit=(1500, 1500),
                ratio=2
            )
        ],
        default='avatars/default_avatar.png',
        render_variations=stdimage_processor,
        blank=False, null=False
    )

    birth_date = models.DateField(blank=True, null=True)

    @property
    def is_admin(self):
        return self.is_active and (self.is_staff or self.groups.filter(name='Administrators').exists())

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        if self.is_staff:
            if not self.groups.filter(name='Administrators').exists():
                administrators = Group.objects.get(name='Administrators')
                self.groups.add(administrators)
        assign_perm('view_tasks_archive', self, self)
        assign_perm('view_contests_archive', self, self)


class Post(models.Model):
    author = models.ForeignKey('User', on_delete=models.SET_NULL, related_name='posts', null=True, blank=True)
    title = models.CharField(max_length=200, blank=False)
    text = models.TextField(blank=False)
    is_important = models.BooleanField(default=False)

    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.now()
        self.modified = datetime.now()
        return super(Post, self).save(*args, **kwargs)


class Comment(MPTTModel):
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey('User', on_delete=models.SET_NULL, related_name='comments', null=True, blank=True)
    text = models.TextField(blank=False)
    image = StdImageField(
        upload_to=CustomUploadTo(
            upload_type='images',
            path='',
            random_filename=True
        ),
        render_variations=False,
        validators=[
            MaxSizeValidator(1500, 1500)
        ],
        blank=True, null=True
    )

    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='answers')

    created = models.DateTimeField(editable=False)
    modified = models.DateTimeField()

    def save(self, *args, **kwargs):
        if not self.id:
            self.created = datetime.now()
        self.modified = datetime.now()
        return super(Comment, self).save(*args, **kwargs)


class Task(models.Model):
    class Meta:
        permissions = (
            ('view_who_solved_task', 'Can view list of users who solved task'),
        )

    author = models.ForeignKey('User', on_delete=models.SET_NULL, related_name='tasks', blank=True, null=True)
    name = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(blank=False, null=True)
    flag = models.CharField(max_length=100, null=False, blank=False)

    solved_by = models.ManyToManyField('User', related_name='solved_tasks', blank=True)

    cost = models.IntegerField(null=False, blank=False, default=50)

    is_published = models.BooleanField(default=False)
    publication_time = models.DateTimeField(default=datetime.fromtimestamp(1529656118))

    tags = models.ManyToManyField('TaskTag', related_name='tasks', blank=True)

    def save(self, *args, **kwargs):

        if self.id:
            old = Task.objects.only('is_published').get(id=self.id)
            if not old.is_published and self.is_published:
                self.publication_time = datetime.now()
        else:
            if self.is_published:
                self.publication_time = datetime.now()

        super(Task, self).save(*args, **kwargs)


class Contest(models.Model):
    class Meta:
        permissions = (
            ('view_unstarted_contest', 'Can view not started contest'),
            ('can_participate_in_contest', 'Can participate in contest')
        )

        ordering = ('-id',)

    author = models.ForeignKey('User', on_delete=models.SET_NULL, related_name='contests', blank=True, null=True)
    title = models.CharField(max_length=100, null=False, blank=False)
    description = models.TextField(blank=True, null=True)
    start_time = models.DateTimeField(default=datetime.fromtimestamp(2051222400))
    end_time = models.DateTimeField(default=datetime.fromtimestamp(2051222500))

    tasks = models.ManyToManyField('Task',
                                   related_name='contests',
                                   blank=True,
                                   through='ContestTaskRelationship')

    participants = models.ManyToManyField('User',
                                          related_name='contests_participated',
                                          blank=True)

    is_published = models.BooleanField(default=False)
    is_running = models.BooleanField(default=False)
    is_finished = models.BooleanField(default=False)
    is_registration_open = models.BooleanField(default=False)

    celery_start_task_id = models.CharField(max_length=50, null=True, blank=True)
    celery_end_task_id = models.CharField(max_length=50, null=True, blank=True)

    def save(self, *args, **kwargs):
        add_start_task = False
        add_end_task = False

        if self.id:
            old = Contest.objects.only('celery_start_task_id',
                                       'celery_end_task_id',
                                       'start_time',
                                       'end_time').get(id=self.id)

            if old.start_time != self.start_time:
                current_app.control.revoke(old.celery_start_task_id)
                result = start_contest.apply_async(args=(self.id,), eta=self.start_time)
                self.celery_start_task_id = result.id

            if old.end_time != self.end_time:
                current_app.control.revoke(old.celery_end_task_id)
                result = end_contest.apply_async(args=(self.id,), eta=self.end_time)
                self.celery_end_task_id = result.id

        else:
            if self.start_time != datetime.fromtimestamp(2051222400):
                add_start_task = True

            if self.end_time != datetime.fromtimestamp(2051222400):
                add_end_task = True

        super(Contest, self).save(*args, **kwargs)

        if add_start_task:
            result = start_contest.apply_async(args=(self.id,), eta=self.start_time)
            Contest.objects.filter(id=self.id).update(celery_start_task_id=result.id)
        if add_end_task:
            result = end_contest.apply_async(args=(self.id,), eta=self.end_time)
            Contest.objects.filter(id=self.id).update(celery_end_task_id=result.id)


class File(models.Model):
    owner = models.ForeignKey('User', on_delete=models.SET_NULL, related_name='files', null=True, blank=True)
    upload_time = models.DateTimeField(editable=False)
    task = models.ForeignKey('Task', on_delete=models.SET_NULL, related_name='files', null=True, blank=True)

    name = models.CharField(max_length=100, null=False, blank=False)

    file_field = CustomFileField(
        upload_to=CustomUploadTo(
            upload_type='files',
            path='',
            append_random=True),
        blank=False, null=False
    )

    def save(self, *args, **kwargs):
        if not self.id:
            self.upload_time = datetime.now()
        super(File, self).save(*args, **kwargs)


class Organization(models.Model):
    name = models.CharField(max_length=200, blank=False)
    description = models.TextField(blank=True)


class TaskTag(models.Model):
    name = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return "Tag object ({}:{})".format(self.id, self.name)


class ContestTaskRelationship(models.Model):
    contest = models.ForeignKey('Contest', on_delete=models.CASCADE, related_name='contest_task_relationship')
    task = models.ForeignKey('Task', on_delete=models.CASCADE, related_name='contest_task_relationship')
    solved = models.ManyToManyField('User', related_name='contest_task_relationship', blank=True)
    cost = models.IntegerField(default=0)

templates/profile_templates/friends.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% block templ %}
    <div class="ui segment">
        <div class="left floated eleven wide column">
            <div class="ui basic vertical left aligned segment {% include "snippets/big_text.html" %}">Rating</div>
        </div>
        <div class="ui clearing divider"></div>
        <table class="ui celled center aligned basic unstackable table">
            <thead>
                <th class="two wide">#</th>
                <th class="nine wide">Name</th>
                <th class="six wide"></th>
            </thead>
            <tbody>
                {% for user in request.user.friends.all %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <a class="rank-{{ user.rank }}" href="{% url 'user_info' user.username %}">
                                {{ user.username }}
                            </a>
                        </td>
                        <td>
                            <i class="{% include "snippets/mini_text.html" %} star icon friends_toggle"
                               friend_id={{ user.id }}></i>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "snippets/pagination.html" with page_name='friends_view_with_page' %}
    </div>

{% endblock %}

templates/profile_templates/profile.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}
{% load custom_tags %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% block templ %}
	<div class="ui bottom attached segment">
		<div class="ui grid">
			<div class="nine wide column">
				<div class="ui grid">
					<div class="row">
						<div class="column">
    						<div class="rank-{{ user.rank }}">Master</div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<div class="{% include "snippets/big_text.html" %} rank-{{ user.rank }}">{{ user.username }}
                            </div>
    						{% if request.user != user and request.user.is_authenticated %}
    							<i class="{% include "snippets/big_text.html" %} star
                                    {% if not request.user|is_friends_with:user %}
                                        outline
                                    {% endif %} icon friends_toggle" friend_id={{ user.id }}>
                                </i>
    						{% endif %}
    					</div>
    				</div>
    				{% if user.first_name and user.last_name or user.country or user.city %}
                		<div class="row">
    						<div class="column">
    							<div class="{% include "snippets/mini_text.html" %}">
    								{% if user.first_name and user.last_name %}
                        				{{ user.first_name|capfirst }} {{ user.last_name|capfirst }}{% if user.country or user.city %}, {% endif %}
                        			{% endif %}
									{% if user.country %}
                        				{{ user.country.name|capfirst }}{% if user.city %}, {% endif %}
                        			{% endif %}
                        			{% if user.city %}
										{{ user.city|capfirst }}
									{% endif %}
    							</div>
							</div>
                		</div>
            		{% endif %}
            		{% if user.organization %}
            			<div class="row">
    						<div class="column">
    							<div class="{% include "snippets/mini_text.html" %}">
    								From organization {{ user.organization.name|capfirst }}
    							</div>
							</div>
                		</div>
                	{% endif %}
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} chart line icon"></i> <div class="{% include "snippets/mini_text.html" %} inline">Rating: </div>
    						<div class="{% include "snippets/mini_text.html" %} rank-{{ user.rank }}">{{ user.cost_sum }}</div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} chart line icon"></i> <div class="{% include "snippets/mini_text.html" %} inline">Maximum rating: </div>
    						<div class="{% include "snippets/mini_text.html" %} rank-{{ user.rank }}">{{ user.cost_sum }}</div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} users icon"></i> <div class="{% include "snippets/mini_text.html" %} inline">Friend of </div>
    						<div class="{% include "snippets/mini_text.html" %} inline">{{ user.befriended_by.count }}</div>
    						<div class="{% include "snippets/mini_text.html" %} inline">users</div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} registered icon"></i> <div class="{% include "snippets/mini_text.html" %} inline">Registered: </div>
    						<div class="{% include "snippets/mini_text.html" %} inline">{{ user.date_joined }}</div>
    					</div>
    				</div>
    				{% if request.user == user %}
        				<div class="row">
        					<div class="column">
        						<i class="{% include "snippets/mini_text.html" %} users icon"></i> <div class="{% include "snippets/mini_text.html" %} inline"><a href="{% url 'friends_view' %}">My friends</a></div>
        					</div>
        				</div>
    				{% endif %}
    				{% if request.user == user %}
        				<div class="row">
        					<div class="column">
        						<i class="{% include "snippets/mini_text.html" %} wrench icon"></i> <div class="{% include "snippets/mini_text.html" %} inline"><a href="{% url 'settings_general_view' %}">Change settings</a></div>
        					</div>
        				</div>
    				{% endif %}
    				<div class="row">
    					<div class="column">
                            <i class="{% include "snippets/mini_text.html" %} book icon"></i>
                            <div class="{% include "snippets/mini_text.html" %} inline"><a
                                    href="{% url 'user_blog_view' user.username %}">Blog</a></div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} tasks icon"></i> <div class="{% include "snippets/mini_text.html" %} inline"><a href="{% url 'user_tasks_view' user.username %}">Tasks</a></div>
    					</div>
    				</div>
    				<div class="row">
    					<div class="column">
    						<i class="{% include "snippets/mini_text.html" %} code icon"></i> <div class="{% include "snippets/mini_text.html" %} inline"><a href="{% url 'user_contests_view' user.username %}">Contests</a></div>
    					</div>
    				</div>
                    <div class="row">
                        <div class="column">
                            <i class="{% include "snippets/mini_text.html" %} question icon"></i> <div class="{% include "snippets/mini_text.html" %} inline"><a href="{% url 'user_solved_tasks_view' user.username %}">Solved tasks</a></div>
                        </div>
                    </div>
    			</div>
			</div>
			<div class="seven wide column">
				<img class="ui medium image" src="{{ user.avatar.main.url }}">
			</div>
		</div>
	</div>

{% endblock %}

templates/profile_templates/settings_general.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% block templ %}
	<div class="ui bottom attached segment">
		 <div class="left floated eleven wide column">
	        <div class="ui basic vertical left aligned segment {% include "snippets/big_text.html" %}">
                {{ request.user.username }}
            </div>
	    </div>
	    <div class="ui clearing divider"></div>
        {% include 'snippets/form_begin.html' with form_name='settings_general_form' action='' %}
			<button class="ui fluid teal button field" id="load_avatar" type="button">
				Load avatar
			</button>
			<div class="field">
				<input id="load_avatar_input" type="file" name="avatar" style="display: none;"/>
			</div>
			<div class="field">
				<input type="text" name="email" placeholder="Email"
                       {% if request.user.email %}value="{{ request.user.email }}"{% endif %} disabled />
			</div>
			<div class="field">
				<input type="text" name="old_password" placeholder="Old password"/>
			</div>
			<div class="field">
				<input type="text" name="new_password" placeholder="New password"/>
			</div>
			<div class="field">
				<input type="text" name="new_password2" placeholder="Retype new password"/>
			</div>
			<button class="ui fluid teal button field" type="submit">Change settings</button>
        {% include 'snippets/form_end.html' with form_name='settings_general_form' %}
	</div>

    <script>
    	$("#load_avatar").click(function() {
	        $("#load_avatar_input").click();
	    });
    </script>
{% endblock %}

templates/profile_templates/user_blog.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% block templ %}

    <div class="ui bottom attached segment">
        <div class="ui grid">
            <div class="left floated nine wide column">
                <div class="ui basic vertical left aligned segment {% include "snippets/big_text.html" %}">{{ user.username }}`s blog</div>
            </div>
            <div class="right floated seven wide column">
                <a class="ui segment center_aligned {% include "snippets/mini_text.html" %}" href="{% url 'post_creation_view' %}">
                    Write post
                </a>
            </div>
        </div>
        <div class="ui clearing divider"></div>
        {% for post in posts %}
            <div class="ui basic padded vertical segment">
                <div class="ui huge header break_word">
                    <a href="{% url 'post_view' post.id %}">
                        {{ post.title }}
                    </a>
                </div>
                By 
                <a class="rank-{{ post.author.rank }}" href="{% url 'user_info' post.author.username %}">
                    {{ post.author.username }}
                </a>
                , {{ post.created }}
                <div class="ui segment markdown">
                    {{ post.text }}
                </div>
            </div>
        {% endfor %}
        {% if posts.count == 0 %}
            <div class="ui huge header">No posts here</div>
        {% else %}
            {% include "snippets/pagination_1_arg.html" with page_name='user_blog_view_with_page' arg1=user.id %}
        {% endif %}
    </div>

{% endblock %}

templates/profile_templates/user_contests.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% load guardian_tags %}

{% block templ %}

    <div class="ui bottom attached segment">
        <div class="ui grid">
            <div class="left floated nine wide column">
                <div class="ui basic vertical left aligned segment {% include "snippets/big_text.html" %}">{{ user.username }}`s contests</div>
            </div>
            {% if request.user == user %}
                {% if perms.website.add_contest %}
                    <div class="right floated seven wide column">
                        <a class="ui segment center_aligned {% include "snippets/mini_text.html" %}" href="{% url 'create_contest' %}">
                            Create contest
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="ui clearing divider"></div>
        <table class="ui celled center aligned basic unstackable table">
            <thead>
                <th class="one wide">#</th>
                <th class="ten wide">Name</th>
                <th class="three wide">Start time</th>
                <th class="two wide"></th>
            </thead>
            <tbody>
                {% for contest in contests %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td class="left aligned">
                            <a href="{% url 'contest_view' contest.id %}">
                                {{ contest.title }}
                            </a>
                        </td>
                        <td>
                            {{ contest.start_time }}
                        </td>
                        <td>
                            <a href="{% url 'contest_view' contest.id %}">Open</a>
                        </td> 
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "snippets/pagination_1_arg.html" with page_name='user_contests_view_with_page' arg1=user.id %}
    </div>

{% endblock %}

templates/profile_templates/users_tasks.html
{% extends "master_templates/common_template.html" %}
{% load staticfiles %}

{% block topbar %}{% include "bar_templates/user_sidebar.html" %}{% endblock %}

{% load guardian_tags %}

{% block templ %}

    <div class="ui bottom attached segment">
        <div class="ui grid">
            <div class="left floated nine wide column">
                <div class="ui basic vertical left aligned segment {% include "snippets/big_text.html" %}">{{ user.username }}`s tasks</div>
            </div>
            {% if request.user == user %}
                {% if perms.website.add_task %}
                    <div class="right floated seven wide column">
                        <a class="ui segment center_aligned {% include "snippets/mini_text.html" %}" href="{% url 'task_creation_view' %}">
                            Create task
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <div class="ui clearing divider"></div>
        <table class="ui celled center aligned basic unstackable table">
            <thead>
                <th class="one wide">#</th>
                <th class="nine wide">Name</th>
                <th class="four wide">Tags</th>
                <th class="one wide">Cost</th>
                <th class="one wide">Solved</th>
            </thead>
            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td class="left aligned">
                            <a href="{% url 'task_view' task.id %}">
                                {{ task.name }}
                            </a>
                        </td>
                        <td>
                            {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
                        </td>
                        <td>
                            {{ task.cost }}
                        </td>
                        <td>
                            {{ task.solved_count }}
                        </td>  
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "snippets/pagination_1_arg.html" with page_name='user_tasks_view_with_page' arg1=user.id %}
    </div>

{% endblock %}